# This workflow will build and push a new container image to Amazon ECR,
# and then will deploy a new task definition to Amazon ECS, when there is a push to the "master" branch.
#
# To use this workflow, you will need to complete the following set-up steps:
#
# 1. Create an ECR repository to store your images.
#    For example: `aws ecr create-repository --repository-name my-ecr-repo --region us-east-2`.
#    Replace the value of the `ECR_REPOSITORY` environment variable in the workflow below with your repository's name.
#
# 2. Create an ECS task definition, an ECS cluster, and an ECS service.
#    For example, follow the Getting Started guide on the ECS console:
#      https://us-east-2.console.aws.amazon.com/ecs/home?region=us-east-2#/firstRun
#    Replace the value of the `ECS_SERVICE` environment variable in the workflow below with the name you set for the Amazon ECS service.
#    Replace the value of the `ECS_CLUSTER` environment variable in the workflow below with the name you set for the cluster.
#
# 3. Store your ECS task definition as a JSON file in your repository.
#    The format should follow the output of `aws ecs register-task-definition --generate-cli-skeleton`.
#    Replace the value of the `ECS_TASK_DEFINITION` environment variable in the workflow below with the path to the JSON file.
#    Replace the value of the `CONTAINER_NAME` environment variable in the workflow below with the name of the container
#    in the `containerDefinitions` section of the task definition.
#
# 4. Store an IAM user access key in GitHub Actions secrets named `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`.
#    See the documentation for each action used below for the recommended IAM policies for this IAM user,
#    and best practices on handling the access key credentials.

name: Deploy to Amazon ECS

on:
  push:
    branches: [ "main", "feature/*", "bugfix/*" ]

#env:
#  ECR_REPOSITORY: person-finder                                       # set this to your Amazon ECR repository name
#  ECS_SERVICE: person-finder                                          # set this to your Amazon ECS service name
#  ECS_SERVICE_QA: person-finder-qa                                    # set this to your Amazon ECS service name
#  ECS_CLUSTER: emerge                                                 # set this to your Amazon ECS cluster name
#  ECS_CLUSTER_QA: emerge-qa                                           # set this to your Amazon ECS cluster name
#  ECS_TASK_DEFINITION_NAME: person-finder                             # set this to your Amazon ECS task definition name
#  ECS_TASK_DEFINITION_NAME_QA: person-finder-qa                       # set this to your Amazon ECS task definition name
#  CONTAINER_NAME: person-finder                                       # set this to the name of the container in the
#  CONTAINER_NAME_QA: person-finder-qa                                 # set this to the name of the container in the
                                                                       # containerDefinitions section of your task definition

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 21
        cache: maven

    - name: Run unit & integration tests
      run: mvn clean verify

#    - name: Configure AWS credentials
#      uses: aws-actions/configure-aws-credentials@v1
#      with:
#        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#        aws-region: ${{ secrets.AWS_REGION }}

#    - name: Set CODEARTIFACT_AUTH_TOKEN
#      run: |
#        export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain emerge --domain-owner 123456789012 --region ap-southeast-1 --query authorizationToken --output text)
#        echo "CODEARTIFACT_AUTH_TOKEN=${CODEARTIFACT_AUTH_TOKEN}" >> $GITHUB_ENV

#    - name: Login to Amazon ECR
#      id: login-ecr
#      uses: aws-actions/amazon-ecr-login@v1

#    - name: Build, tag, and push image to Amazon ECR
#      id: build-image
#      env:
#        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#        IMAGE_TAG: ${{ github.sha }}
#        CODEARTIFACT_AUTH_TOKEN: ${{ env.CODEARTIFACT_AUTH_TOKEN }}  # Pass the CODEARTIFACT_AUTH_TOKEN as an environment variable
#      run: |
        # Build a docker container and
        # push it to ECR so that it can
        # be deployed to ECS.
#        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG --build-arg CODEARTIFACT_AUTH_TOKEN=$CODEARTIFACT_AUTH_TOKEN .
#        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
#        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

#    - name: Download Amazon ECS task definition (prod)
#      if: github.ref == 'refs/heads/main'
#      run: |
#        aws ecs describe-task-definition --task-definition ${{ env.ECS_TASK_DEFINITION_NAME }} --query taskDefinition > task-definition.json

#    - name: Download Amazon ECS task definition (qa)
#      if: github.ref != 'refs/heads/main'
#      run: |
#        aws ecs describe-task-definition --task-definition ${{ env.ECS_TASK_DEFINITION_NAME_QA }} --query taskDefinition > task-definition.json

#    - name: Fill in the new image ID in the Amazon ECS task definition (prod)
#      if: github.ref == 'refs/heads/main'
#      id: task-def
#      uses: aws-actions/amazon-ecs-render-task-definition@v1
#      with:
#        task-definition: task-definition.json
#        container-name: ${{ env.CONTAINER_NAME }}
#        image: ${{ steps.build-image.outputs.image }}

#    - name: Fill in the new image ID in the Amazon ECS task definition (qa)
#      if: github.ref != 'refs/heads/main'
#      id: task-def
#      uses: aws-actions/amazon-ecs-render-task-definition@v1
#      with:
#        task-definition: task-definition.json
#        container-name: ${{ env.CONTAINER_NAME_QA }}
#        image: ${{ steps.build-image.outputs.image }}

#    - name: Deploy Amazon ECS task definition (prod)
#      if: github.ref == 'refs/heads/main'
#      uses: aws-actions/amazon-ecs-deploy-task-definition@v2
#      with:
#        task-definition: ${{ steps.task-def.outputs.task-definition }}
#        service: ${{ env.ECS_SERVICE }}
#        cluster: ${{ env.ECS_CLUSTER }}
#        wait-for-service-stability: true

#    - name: Deploy Amazon ECS task definition
#      if: github.ref != 'refs/heads/main'
#      uses: aws-actions/amazon-ecs-deploy-task-definition@v2
#      with:
#        task-definition: ${{ steps.task-def.outputs.task-definition }}
#        service: ${{ env.ECS_SERVICE_QA }}
#        cluster: ${{ env.ECS_CLUSTER_QA }}
#        wait-for-service-stability: true
